defmodule McpNotes.Repo.Migrations.AddOnDelete do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # drop constraint(:notes, "notes_project_id_fkey")

    # alter table(:notes) do
    #   modify :project_id,
    #          references(:projects,
    #            column: :id,
    #            name: "notes_to_projects_fkey",
    #            type: :uuid,
    #            on_delete: :delete_all
    #          )
    # end

    # execute("ALTER TABLE notes alter CONSTRAINT notes_to_projects_fkey NOT DEFERRABLE")
  end

  def down do
    # drop constraint(:notes, "notes_to_projects_fkey")

    alter table(:notes) do
      modify :project_id,
             references(:projects, column: :id, name: "notes_project_id_fkey", type: :uuid)
    end
  end
end
