defmodule McpNotes.Repo.Migrations.Rmeove do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # alter table(:projects) do
    # Attribute removal has been commented out to avoid data loss. See the migration generator documentation for more
    # If you uncomment this, be sure to also uncomment the corresponding attribute *addition* in the `down` migration
    # remove :archived_at
    # end
    # 
    # alter table(:notes) do
    # Attribute removal has been commented out to avoid data loss. See the migration generator documentation for more
    # If you uncomment this, be sure to also uncomment the corresponding attribute *addition* in the `down` migration
    # remove :archived_at
    # end
    # 
  end

  def down do
    # alter table(:notes) do
    # This is the `down` migration of the statement:
    #
    #     remove :archived_at
    #
    # 
    # add :archived_at, :utc_datetime_usec
    # end
    # 
    # alter table(:projects) do
    # This is the `down` migration of the statement:
    #
    #     remove :archived_at
    #
    # 
    # add :archived_at, :utc_datetime_usec
    # end
    # 
  end
end